version: '3'
services:
  web:
    build: ./nginx
    volumes:
      - php-fpm-socket:/var/run/php-fpm 
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./project/html:/var/www/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php
      - mysql
      - redis
  php:
    build: ./php
    volumes:
      - php-fpm-socket:/var/run/php-fpm 
      - ./project/html:/var/www/html
    restart: always
  mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/logs:/var/log/mysql
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    volumes:
      - ./redis/data:/data

volumes:
  php-fpm-socket:
